""" NOTE: This piece of code has been generated by ChatGPT 5.3, 
while creating the roadmap, it told me to use sympy, 
so I learned a little bit of it and I really didn't want to waste my knowledge so yeah, it exits here
"""

from sympy import Matrix, lcm

def balance_sympy(moleculeParser):
    reactants, products = moleculeParser
    compounds = reactants + products

    # collect all elements
    elements = set()
    for c in compounds:
        elements.update(c.keys())
    elements = list(elements)

    # build stoichiometric matrix
    matrix = []
    for element in elements:

        row = []

        for compound in reactants:
            row.append(compound.get(element,0))

        for compound in products:
            row.append(-compound.get(element,0))

        matrix.append(row)

    M = Matrix(matrix)

    # find nullspace (solution to Ax = 0)
    null = M.nullspace()[0]

    # convert fractions → integers
    multiplier = lcm([x.q for x in null])
    coeffs = [int(x * multiplier) for x in null]

    left = coeffs[:len(reactants)]
    right = coeffs[len(reactants):]

    return format_equation(moleculeParser, left, right)


def format_equation(moleculeParser, left, right):

    reactants, products = moleculeParser

    def format_compound(compound, coeff):
        s = "" if coeff == 1 else str(coeff)
        for e in compound:
            s += e
            if compound[e] != 1:
                s += str(compound[e])
        return s

    left_side = " + ".join(
        format_compound(c,left[i]) for i,c in enumerate(reactants)
    )

    right_side = " + ".join(
        format_compound(c,right[i]) for i,c in enumerate(products)
    )

    return left_side + " ---> " + right_side


print(format_equation(([{'C': 1, 'O': 2}, {'H': 2, 'O': 1}], [{'C': 6, 'H': 12, 'O': 6}, {'O': 2}]), [6, 6], [1, 6])) 
# second and third arguements are recieved from the output of the first func (balance_sympy)